### ISSUE TITLE
Browsersync doesn't work sometimes

### ISSUE THREAD

**Issue by raunakhajela** [manjumjn/gulp-with-tailwindcss#2]
When I add tw classes it doesn't update the webpage although the page reloads, I have to type npm run dev command, again and again, to make it work.

**Comment by manjumjn** [comment]
Yes, I reproduced and checked the issue. It was just updating HTML files on gulp watch since we used PurgeCSS to remove unused CSS classes from **style.css** when HTML was updated but styles were not. Fixed it now. Here is the commit [link](https://github.com/manjumjn/gulp-with-tailwindcss/commit/6e64f1a4620b0e908fd900de3dcefe6d9104180a)
